### ISSUE TITLE
never modify system folders

### ISSUE THREAD

**Issue by ykne** [RPM-Outpost/gitkraken#2]
instead of
```
cd /usr/lib64
ln -s -f libcurl.so.4 libcurl-gnutls.so.4
```
install a symlink
`ln -s /usr/lib64/libcurl.so.4 /opt/gitkraken/libcurl-gnutls.so.4`
or even better, add a symlink element in the package.
`/opt/gitkraken/libcurl-gnutls.so.4 -> /usr/lib64/libcurl.so.4`

**Comment by TheElectronWill** [comment]
Adding it in the package seems to be a good idea, I didn't know it was possible with `->`. I'll try it. Thanks!

**Comment by ykne** [comment]
I actually meant "adding to the list of packaged files" not creating the link post factum.
Please add this symlink to %files section.
There is absolutely no need to use a %post for this, creating problems with upgrade and uninstall.
